/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.sound.midi.InvalidMidiDataException;
import org.jfugue.midi.MidiFileManager;
import org.jfugue.pattern.Pattern;
import org.staccato.StaccatoParser;
import principal.NotasEnOctava;

/**
 *
 * @author Nicte
 */
public class Juego extends javax.swing.JFrame {

    private NotasEnOctava listener;
    private StaccatoParser parser;
    private static final int JUEGO_FACIL = 0;
    private static final int JUEGO_MEDIO = 1;
    private static final int JUEGO_DIFICIL = 2;

    public Juego() {
        initComponents();
        
        //alistando conexion serial
        initConex();
        
        //configurando botones de facil, medio, y dificil
        this.buttonGroup1.add(this.jRadioButton1);
        this.buttonGroup1.add(this.jRadioButton2);
        this.buttonGroup1.add(this.jRadioButton3);
        ActionListener miEvento = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (e.getSource() == jRadioButton1) {
                    listener.enviarDatoArduino(JUEGO_FACIL);
                } else if (e.getSource() == jRadioButton2) {
                    listener.enviarDatoArduino(JUEGO_MEDIO);
                } else if (e.getSource() == jRadioButton3) {
                    listener.enviarDatoArduino(JUEGO_DIFICIL);
                }
            }
        };
        this.jRadioButton1.addActionListener(miEvento);
        this.jRadioButton2.addActionListener(miEvento);
        this.jRadioButton3.addActionListener(miEvento);

//añadiendo el model al combo box
        this.cListaMidis.setModel(new ComboModel());
    }
    
    private void initConex(){
        listener = NotasEnOctava.getInstance();
        listener.setFrame(this);
        listener.connect();
        parser = new StaccatoParser();
        parser.addParserListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        bCargarMidi = new javax.swing.JButton();
        cListaMidis = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButton1.setText("Facil");

        jRadioButton2.setText("Medio");

        jRadioButton3.setText("Dificil");

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bCargarMidi.setText("Cargar Midi");
        bCargarMidi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCargarMidiActionPerformed(evt);
            }
        });

        cListaMidis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cListaMidis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cListaMidisActionPerformed(evt);
            }
        });

        jLabel1.setText("JUGAR");

        jMenu1.setText("Inicio");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Jugar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Acerca de.....");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cListaMidis, 0, 229, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCargarMidi, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addComponent(cListaMidis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(bCargarMidi)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCargarMidiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCargarMidiActionPerformed
        Pattern pattern = null;
        try {
            pattern = MidiFileManager.loadPatternFromMidi(new File("midi//" + this.cListaMidis.getSelectedItem().toString()));
            parser.parse(pattern);
            listener.index_lista_notas = 0;
            listener.parseOutput();            
        } catch (IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "No ha escogido un archivo midi.",
                    "Advertencia", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (InvalidMidiDataException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "El archivo midi elegido "
                    + "no cumple con los \nprotocolos, por lo que no se cargó.",
                    "Advertencia", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

//        JFileChooser filechooserabrir = new JFileChooser();
//        filechooserabrir.setFileSelectionMode(JFileChooser.FILES_ONLY);
//        int seleccion = filechooserabrir.showOpenDialog(this);
//        if (seleccion == JFileChooser.APPROVE_OPTION) {
//            try {
//                BufferedReader bufferreader;
//                File file = filechooserabrir.getSelectedFile();
//                cListaMidis.addItem(file.getAbsolutePath());
//                bufferreader = new BufferedReader(new FileReader(file.getAbsolutePath()));
//                String linea, contenido = "";
//
//            } catch (IOException ex) {
//            }
//        }

    }//GEN-LAST:event_bCargarMidiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cListaMidisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cListaMidisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cListaMidisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCargarMidi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cListaMidis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
